plugin 'cocoapods-keys', {
  project: 'Tests',
  keys: [
    'XirSysUsername',
    'XirSysSecretKey'
  ]}

target 'XirSys', :exclusive => true do
  pod 'XirSys', :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
